#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [4]:
import pandas as pd
data_path = '../data/supermarket_sales.csv'
df = pd.read_csv(data_path)

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [14]:
df.groupby('Branch')['Total'].sum()

Branch
A    106200.3705
B    106197.6720
C    110568.7065
Name: Total, dtype: float64

In [15]:
df.groupby('Branch')['Total'].sum().nlargest(1)

Branch
C    110568.7065
Name: Total, dtype: float64

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [60]:
df.groupby(['City','Branch'])['Total'].sum().idxmax()

('Naypyitaw', 'C')

Філіал з найвищим прибутком знаходиться у місті Naypyitaw, це філіал С

In [78]:
df.groupby('City').agg(avg_check=('Total','mean'),transactions=('Invoice ID','count'))

            avg_check  transactions
City
Mandalay   319.872506           332
Naypyitaw  337.099715           328
Yangon     312.354031           340

Також, в місті Naypyitaw найвищій середній чек, тому тут можна розмітисти ще один магазин

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [36]:
invoices_by_category = df.pivot_table(index = ['Branch'], columns= ['Product line'], values = 'Invoice ID', aggfunc= "count")
invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [58]:
invoices_by_category.nlargest(1, 'Electronic accessories')

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

1. Яка категорія товарів продається найгірше?

In [81]:
df.groupby('Product line')['Total'].sum().sort_values()

Product line
Health and beauty         49193.7390
Home and lifestyle        53861.9130
Fashion accessories       54305.8950
Electronic accessories    54337.5315
Sports and travel         55122.8265
Food and beverages        56144.8440
Name: Total, dtype: float64

Найгірше продається Health and beauty Health and beauty, пропоную зробити акції та зменшити закупівлю товарів

Чи є категорія з високим середнім чеком, але низькою кількістю продажів?

In [82]:
df.groupby('Product line')['Total'].agg(['mean', 'count']).sort_values('mean', ascending=False)

                              mean  count
Product line
Home and lifestyle      336.636956    160
Sports and travel       332.065220    166
Health and beauty       323.643020    152
Food and beverages      322.671517    174
Electronic accessories  319.632538    170
Fashion accessories     305.089298    178

Категорія Home and lifestyle з високим середнім чеком, але низькою кількістю продажів, це товари преміальні
Можна запіустити маркетингову підтримку та розмістити товар на видному місціб щоб збільшити продажі

3. Чи залежить середній чек від типу клієнта (Member vs Normal)?

In [85]:
df.groupby('Customer type')['Total'].agg(['mean', 'sum', 'count']).sort_values('mean', ascending=False)

                     mean         sum  count
Customer type
Member         327.791305  164223.444    501
Normal         318.122856  158743.305    499

Member витрачають більше потрібно розвивати програму лояльності